apiVersion: v1
kind: Pod
metadata:
  name: kuard-config
  labels:
    app: kuard-config
spec:
  containers:
    - name: test-container
      image: hellodk/kuard-amd64:1
      imagePullPolicy: Always
      volumeMounts:
        - name: config-volume
          mountPath: /config
      ports:
        - containerPort: 8080
        name: http
        protocol: TCP
  volumes:
    - name: config-volume
      configMap:
        name: game-config
  restartPolicy: Never

---

kind: Service
apiVersion: v1
metadata:
  name: kuard-service
spec:
  selector:
    app: kuard-config
  ports:
    - port: 8080
